### PR TITLE
Swift 4 compatibility with updated podspec

### PR DESCRIPTION
**Pull request by ptseng**
I hope this is helpful for people who would like to use Mockingjay in their Swift 4 projects 😄

### CODE REVIEW

**Comment by seifscape** [comment]
Does anyone know when this will be merged in?

**Comment by ntokozotep** [comment]
@kylef Hi Kyle. Please review this pull request.

**Comment by bredfield** [comment]
Since this hasn't gotten pulled in yet - does anyone know how to reference a commit assigned to a PR via cocoapods? I've tried referencing the branch and the commit, neither work.

**Comment by kylef** [comment]
Pulled in some of these changes and released 2.0.1 https://github.com/kylef/Mockingjay/releases/tag/2.0.1

**Pull request closed without merging**
