### PR TITLE
Fix Carthage build errors

### PR DESCRIPTION
**Pull request by taiheng**
Fixes issues in kylef/mockingjay#29

### CODE REVIEW

**Comment by TomasLinhart** [comment]
Could be this revision or any after this one tagged with Git so it works nicely with Carthage?. Eg. 1.1.1.

**Comment by kylef** [comment]
@TomasLinhart There are a couple of other changes left to make and then we'll tag a 1.1.1 release.

**Comment by TomasLinhart** [comment]
@kylef Ok, thanks.

**Comment by TomasLinhart** [comment]
I have tried to use `master` with Carthage and it seems not to work.

```
*** Building scheme "Mockingjay" in Mockingjay.xcodeproj
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64 /MyProject/Carthage/Checkouts/Mockingjay/Mockingjay/Matchers.swift
	CompileSwift normal x86_64 /MyProject/Carthage/Checkouts/Mockingjay/Mockingjay/Mockingjay.swift
	CompileSwift normal x86_64 /MyProject/Carthage/Checkouts/Mockingjay/Mockingjay/XCTest.swift
	CompileSwift normal x86_64 /MyProject/Carthage/Checkouts/Mockingjay/Mockingjay/NSURLSessionConfiguration.swift
	CompileSwift normal x86_64 /MyProject/Carthage/Checkouts/Mockingjay/Mockingjay/MockingjayProtocol.swift
	CompileSwift normal x86_64 /MyProject/Carthage/Checkouts/Mockingjay/Mockingjay/Builders.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(7 failures)
/MyProject/Carthage/Checkouts/Mockingjay/URITemplate/URITemplate/URITemplate.swift:262:12: warning: 'CFURLCreateStringByAddingPercentEscapes' was deprecated in iOS 9.0: Use [NSString stringByAddingPercentEncodingWithAllowedCharacters:] instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent (since each URL component or subcomponent has different rules for what characters are valid).
/MyProject/Carthage/Checkouts/Mockingjay/URITemplate/URITemplate/URITemplate.swift:262:12: warning: 'CFURLCreateStringByAddingPercentEscapes' was deprecated in iOS 9.0: Use [NSString stringByAddingPercentEncodingWithAllowedCharacters:] instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent (since each URL component or subcomponent has different rules for what characters are valid).
/MyProject/Carthage/Checkouts/Mockingjay/Mockingjay/Matchers.swift:10:8: error: module file's minimum deployment target is ios9.1 v9.1: /Users/Me/Library/Developer/Xcode/DerivedData/Mockingjay-bokxddkvlwcefggcbqojmhvobhtz/Build/Products/Release-iphonesimulator/URITemplate.framework/Modules/URITemplate.swiftmodule/x86_64.swiftmodule
/MyProject/Carthage/Checkouts/Mockingjay/Mockingjay/Matchers.swift:10:8: error: module file's minimum deployment target is ios9.1 v9.1: /Users/Me/Library/Developer/Xcode/DerivedData/Mockingjay-bokxddkvlwcefggcbqojmhvobhtz/Build/Products/Release-iphonesimulator/URITemplate.framework/Modules/URITemplate.swiftmodule/x86_64.swiftmodule
/MyProject/Carthage/Checkouts/Mockingjay/Mockingjay/Matchers.swift:10:8: error: module file's minimum deployment target is ios9.1 v9.1: /Users/Me/Library/Developer/Xcode/DerivedData/Mockingjay-bokxddkvlwcefggcbqojmhvobhtz/Build/Products/Release-iphonesimulator/URITemplate.framework/Modules/URITemplate.swiftmodule/x86_64.swiftmodule
/MyProject/Carthage/Checkouts/Mockingjay/Mockingjay/Matchers.swift:10:8: error: module file's minimum deployment target is ios9.1 v9.1: /Users/Me/Library/Developer/Xcode/DerivedData/Mockingjay-bokxddkvlwcefggcbqojmhvobhtz/Build/Products/Release-iphonesimulator/URITemplate.framework/Modules/URITemplate.swiftmodule/x86_64.swiftmodule
/MyProject/Carthage/Checkouts/Mockingjay/Mockingjay/Matchers.swift:10:8: error: module file's minimum deployment target is ios9.1 v9.1: /Users/Me/Library/Developer/Xcode/DerivedData/Mockingjay-bokxddkvlwcefggcbqojmhvobhtz/Build/Products/Release-iphonesimulator/URITemplate.framework/Modules/URITemplate.swiftmodule/x86_64.swiftmodule
/MyProject/Carthage/Checkouts/Mockingjay/Mockingjay/Matchers.swift:10:8: error: module file's minimum deployment target is ios9.1 v9.1: /Users/Me/Library/Developer/Xcode/DerivedData/Mockingjay-bokxddkvlwcefggcbqojmhvobhtz/Build/Products/Release-iphonesimulator/URITemplate.framework/Modules/URITemplate.swiftmodule/x86_64.swiftmodule
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64 /MyProject/Carthage/Checkouts/Mockingjay/Mockingjay/Matchers.swift
	CompileSwift normal x86_64 /MyProject/Carthage/Checkouts/Mockingjay/Mockingjay/Mockingjay.swift
	CompileSwift normal x86_64 /MyProject/Carthage/Checkouts/Mockingjay/Mockingjay/XCTest.swift
	CompileSwift normal x86_64 /MyProject/Carthage/Checkouts/Mockingjay/Mockingjay/NSURLSessionConfiguration.swift
	CompileSwift normal x86_64 /MyProject/Carthage/Checkouts/Mockingjay/Mockingjay/MockingjayProtocol.swift
	CompileSwift normal x86_64 /MyProject/Carthage/Checkouts/Mockingjay/Mockingjay/Builders.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(7 failures)
```

**Pull request merged**
